<a href="https://colab.research.google.com/github/DUNGTK2004/Pytorch-Tutorial/blob/main/Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.0+cu121'

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Check the number of dimensions of vector
vector.ndim

1

In [8]:
# Check shape of vector
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# Check number of dimensions
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [14]:
# Check shape of TENSOR
TENSOR.shape

torch.Size([1, 3, 3])